name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4o"
  OPENAI_JSON_MODE:
    description: "Enables json mode if true."
    required: false
    default: "true"
  label:
    description: "Label to trigger AI code review."
    required: false
    default: ""
  custom_prompts:
    description: "Custom commands to augment the agent's prompts with. Each line is an individual command."
    required: false
    default: ""
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
  AZURE_OPENAI_DEPLOYMENT:
    description: "Azure OpenAI deployment name"
    required: false
    default: ""
  AZURE_OPENAI_ENDPOINT:
    description: "Azure OpenAI endpoint. Example: https://example-resource.azure.openai.com/"
    required: false
    default: ""
  AZURE_OPENAI_API_VERSION:
    description: "Azure OpenAI API version. Example: 2023-07-01-preview"
    required: false
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
